### ISSUE TITLE
Fritzing Component?

### ISSUE THREAD

**Issue by rwaldron** [sparkfun/Edison_GPIO_Block#3]
Is there any chance of adding a fritzing component for this block?

**Comment by ToniCorinne** [comment]
@HelloTechie Could we get this added in to the Fritzing repo?

**Comment by AltaOhms** [comment]
Let me put it on the list! The main connector won't be usable, but the pins would be. Is that okay?

**Comment by ToniCorinne** [comment]
I don't have any problem with that personally.

**Comment by AltaOhms** [comment]
Awesome! Will post when completed. :)

**Comment by AltaOhms** [comment]
Reorganized Fritzing and this part can be found here: https://github.com/sparkfun/Fritzing_Parts/commit/9dca354bc97bc871e642fe05f99ecdcb9647cb63

Sorry for the wait!
