### ISSUE TITLE
Issues Enabling PWM Pins

### ISSUE THREAD

**Issue by mikekberg** [sparkfun/Edison_GPIO_Block#4]
Is there any documentation regarding enabling the PWM pins? I've tried enabling the GPIO pin and PWM channel for the given pin and I'm not able to get PWM to work. Is there a requirement to set pin muxing like the ardino breakout board?

**Comment by ShawnHymel** [comment]
If you are using MRAA, you can use the PWM class: http://iotdk.intel.com/docs/master/mraa/classmraa_1_1_pwm.html

**Comment by mikekberg** [comment]
How can I push to these using echo's to the filesystem? I think I might just be missing the command to set the Pinmode to PWM. How is that done?

**Comment by ShawnHymel** [comment]
You'll have to set the pin mode. Here's the best documentation I've found: http://www.emutexlabs.com/project/215-intel-edison-gpio-pin-multiplexing-guide

**Comment by mikekberg** [comment]
I'm using the following:

echo mode1 > /sys/kernel/debug/gpio_debug/gpio12/current_pinmux
echo 0 > /sys/class/pwm/pwmchip0/export
echo 20000000 > /sys/class/pwm/pwmchip0/pwm0/period
echo 1080000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable

this should in theory push a signal down the PWM0 channel. The previous post is documentation for the ardino breakout board which requires setting a number of pins to disable internal pull up resistors and set the direction of the pin. These pins are not present with the GPIO block (write errors when I try writing to them).

**Comment by ShawnHymel** [comment]
I don't have an Edison in front of me right now to test this, but for now, see if [this article](https://theiotlearninginitiative.gitbooks.io/inteledison/content/documentation/PinMuxing.html) or [this post](https://communities.intel.com/thread/45986?start=0&) helps at all. 

Also, how are you measuring PWM? The level shifters on the GPIO block have a hard time driving any amount of current (even 1 or 2 mA). Are you using a scope or connecting an LED, etc.?

**Comment by mhord** [comment]
I've sweated through this myself, quite a bit. I feel like I eventually got it working but it's been awhile.

Your best bet is probably to [look at how Intel's mraa library](https://github.com/intel-iot-devkit/mraa/blob/master/src/pwm/pwm.c) does it; they're basically just constructing strings and pushing them into the files. I'm not saying it'll be easy; there are a lot of layers of conditionals and #define statements to dig through, but it will at least give you some idea of where you're headed.

**Comment by mikekberg** [comment]
Thanks, That helps out a ton. I'll do some digging and see if I can post a solution for anyone else looking.

**Comment by mikekberg** [comment]
So I've taken a look through the source and the code I posted above does work. I was initially running on lower current and like @ShawnHymel commented about the current was too low to see an LED turn on. 

Looks like the GPIO board follows the same mux'ing requirements the ardino breakout board uses. Thanks everyone!

**Comment by AbhiKag** [comment]
Hey, I seem to be stuck at the same spot. Could you tell me how you worked around this (any config/hardware setup) ?

**Comment by mikekberg** [comment]
Yes! I did get this going. I'll dig up the source code and post it. Are you looking to do it through bash shell or are you writing code? what language?

**Comment by mikekberg** [comment]
This worked for me from bash this enables the PWM0 pin (second from the bottom on the left)

Enable Pin12 -> echo 12 > /sys/class/gpio/export
Set as an output pin -> echo out > /sys/class/gpio/gpio12/direction
Set the mode as PWM -> echo mode1 > /sys/kernel/debug/gpio_debug/gpio12/current_pinmux
Enable pwm0 -> echo 0 > /sys/class/pwm/pwmchip0/export
set period -> echo 20000000 > /sys/class/pwm/pwmchip0/pwm0/period
set duty cycle -> echo 1080000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
turn on pwm -> echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable

**Comment by AbhiKag** [comment]
Thanks for the prompt response!
I will try this out.
For me, the sparkfun gpio board pwm pins are giving out a very low current (almost unusable).
Did you experience something similar, and if so, is there any solution?
I am open to any option, bash or c++! MRAA doesn't seem to be working though (maybe a platform recognition issue?) .

**Comment by ShawnHymel** [comment]
In its normal operation, the TXB0108 (the level shifter on the GPIO Block) cannot source more than about 5 mA, which is barely enough to power an LED. I generally use a transistor to connect LEDs to the GPIO Block, like in [this example](https://learn.sparkfun.com/tutorials/installing-libmraa-on-ubilinux-for-edison#the-circuit).
